eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka
server:
  port: 9999
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-share:
        path: /base/service/share/**
        service-id: config-client
    api-user:
        path: /base/service/share/**
        service-id: config-client