server:
  port: 8888
spring:
  application:
    name: config-service
  #profiles:
    #active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/toGream/SpringcloudConfig
          search-paths: respo
          username:
          password:
      label: master
#eureka:
  #client:
    #service-url: 
      #defaultZone: http://localhost:8761/eureka